name: Type Check (mypy)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies (including dev)
        run: uv sync --locked --dev

      - name: Run mypy
        run: uv run mypy src

